apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore   # the name you will reference in your app
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6379"
    - name: redisPassword
      value: ""    # set password if your Redis requires auth
    - name: enableTLS
      value: "false"
    - name: ttlInSeconds
      value: 60
scopes:
  - pmu-be   # optional: limit to specific app-id
